api-version: '1.19'
name: DummyLobby
version: '0.1.0'
main: net.cherrycave.dummylobby.DummyLobbyPlugin
loader: net.cherrycave.dummylobby.DummyLobbyPluginLoader
description: Paper Example Plugin
authors: ["StckOverflw"]

has-open-classloader: true

load-after:
  - name: LuckPerms
    bootstrap: true

dependencies:
  - name: LuckPerms
    required: true
    bootstrap: true